# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'clothing.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'


field_separator: "\t"

# n_ui_layers: [1, 2, 3, 4]
n_ui_layers: [2]
# n_mm_layers: [0, 1, 2, 3, 4]
n_mm_layers: [2]
# n_hyper_layer: [1, 2, 3, 4]
n_hyper_layer: [2]

# hyper_num: [2, 4, 8, 16, 32, 64, 128, 256]
hyper_num: [64]
# keep_rate: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
keep_rate: [0.2]
# alpha: [-0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1.0,0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
alpha: [-0.9]
# beta: [-0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1.0,0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
beta: [0.8]
# cl_weight : [0.0, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 0.1]
cl_weight : [1e-04]
# reg_weight : [0.0, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 0.1]
reg_weight: [1e-06]